services:
  scoring:
    build: .
    image: ml-scoring-service:latest
    container_name: ml-scoring-service
    volumes:
      - ./input:/app/input
      - ./output:/app/output

  trainer:
    build: .
    image: ml-scoring-service:latest
    profiles: ["train"]
    volumes:
      - ./models:/app/models
    command: ["python", "-m", "src.train"]
